### ISSUE TITLE
User accounts

### ISSUE THREAD

**Issue by chuckdries** [ViciousFish/buzzwords#3]
> Hey http://Buzzwords.gg i'm lovign the game same with my mom. Is there any way to add authentication, like users and accounts. Or other cookie sharing. I want to be able to play both on ipad and kindle. God bless

https://twitter.com/gestaltbb/status/1480018946191507457

**Comment by James-Quigley** [comment]
We'll probably want to expand our authentication options, but for now, Sign in with Google has been implemented
