### ISSUE TITLE
Handle no vowel game state

### ISSUE THREAD

**Issue by KorySchneider** [ViciousFish/buzzwords#44]
The game can reach a state where a player cannot make any words.

Currently, nothing happens and the game must be abandoned.

Potential solutions:
- Ensure at least one vowel is on the board at all times
- When this state is reached, the player with the most tiles wins
- When this state is reached, all tiles reset
- The game is a draw

Loving the game!

![screenshot](https://user-images.githubusercontent.com/5200816/150470545-e8855be7-c0ad-4d2e-b5f1-925a56fbe2d3.png)

**Comment by chuckdries** [comment]
Interesting, there's definitely code in there that attempts to ensure there's always a vowel and a playable word on the board. Thanks for the bug report

**Comment by James-Quigley** [comment]
I've improved the algorithm a little bit, so this should no longer be possible. If it can't randomly generate valid letter combinations, it will just select the letters from a known valid word and inject them.
