### ISSUE TITLE
Bot plays profanity

### ISSUE THREAD

**Issue by chuckdries** [ViciousFish/buzzwords#46]
![buzzword-slur](https://user-images.githubusercontent.com/1351436/150608259-83300aa2-6cc3-4c61-b019-07e5113d08bf.png)

SPIC is a slur for hispanic people, which is not in our banned words list but in general we should be cross-referencing the banned words list for bot plays

**Comment by James-Quigley** [comment]
We can just remove the words from our valid word list, which will prevent players and bots from using the words. Looks like its already been done for the word mentioned here. I'll remove a few others as well

**Comment by chuckdries** [comment]
works for me
