### ISSUE TITLE
dictionary lookup for words

### ISSUE THREAD

**Issue by chuckdries** [ViciousFish/buzzwords#47]

**Comment by BryceBeagle** [comment]
Dictionary lookup seems to use a different source than wordlist: ![Screenshot_20220124-233508.png](https://user-images.githubusercontent.com/5437880/150932131-65e8f483-85bf-4a7b-b404-e0757b15e80e.png)

**Comment by chuckdries** [comment]
Also sometimes words that definitely exist in the dictionary 404 randomly after taking forever to load. No clue on that one, that's gotta be the free dictionary api's problem. Yet another reason to switch dictionary APIs I guess

**Comment by chuckdries** [comment]
Closing in favor of #50
