### ISSUE TITLE
backend crash (caused by nudge?)

### ISSUE THREAD

**Issue by chuckdries** [ViciousFish/buzzwords#75]
![image](https://user-images.githubusercontent.com/1351436/156293974-d24e8dc6-0558-44dd-a23b-53cc0d3f8cb6.png)

**Comment by chuckdries** [comment]
![image](https://user-images.githubusercontent.com/1351436/156294074-8c9497d5-dec3-4d28-9568-b5ccbf74eb36.png)

**Comment by James-Quigley** [comment]
I believe this has been fixed at some point? Feel free to reopen if you encounter it again though
