### ISSUE TITLE
stuck game, crashes backend when nudged

### ISSUE THREAD

**Issue by chuckdries** [ViciousFish/buzzwords#99]
https://buzzwords.gg/play/TGDfe53w4Dk8pyoM8sObE

nudge the bot -> backend will crash

logs: https://logtail.com/team/54028/tail?s=112847&a=1658439148205.2ac7fdb3-6ec7-430c-8d5f-8bd4f5b68b37

**Comment by James-Quigley** [comment]
I don't even see an option to nudge the bot. The game is over?

**Comment by chuckdries** [comment]
Yeah I think you fixed it with #102
